export const GET_ACCESS_TOKEN='GET_ACCESS_TOKEN';
export const REFRESH_ACCESS_TOKEN='REFRESH_ACCESS_TOKEN';
export const GET_CRM_USERS="GET_CRM_USERS";
export const GET_CURRENT_USER_ID="GET_CURRENT_USER_ID";