export const SET_ACCESS_TOKEN='SET_ACCESS_TOKEN';
export const REFRESH_ACCESS_TOKEN='REFRESH_ACCESS_TOKEN';
export const GET_CRM_USERS="GET_CRM_USERS";
export const GET_CURRENT_USER_ID="GET_CURRENT_USER_ID";
export const SET_ENTITIES="SET_ENTITIES";
export const SET_ENTITIES_VIEW_DATA="SET_ENTITIES_VIEW_DATA";
export const SET_ENTITIES_ATTRIBUTE_COLLECTION="SET_ENTITIES_ATTRIBUTE_COLLECTION";

export const SET_CURRENT_USER="SET_CURRENT_USER";
export const SET_CURRENT_CONNECTION="SET_CURRENT_CONNECTION";

export const SET_CURRENT_MSAL_PUBLIC_CLIENT="SET_CURRENT_MSAL_PUBLIC_CLIENT";
export const SET_CURRENT_MSAL_CONFIDENTIAL_CLIENT="SET_CURRENT_MSAL_CONFIDENTIAL_CLIENT";
export const SIGNOUT_USER="SIGNOUT_USER";



export const SET_APPS="SET_APPS";