import { CLIVerb, IntelliSenseType } from "../../../../interfaces/CliIntelliSense";



export const ACTION_PARAM_ENTITY_NAME = "entity";
export const ACTION_PARAM_ATTRIBUTE_NAME = "attribute";
export const ACTION_PARAM_PROPERTIES_NAME = "properties";
export const ACTION_PARAM_FILTER_NAME = "filter";
export const ACTION_PARAM_FILTER_OPERATOR_NAME = "filteroperator"
export const ACTION_PARAM_EXPAND_NAME = "expand";


export const ACTION_PARAM_ATTRIBUTE_ALL_NAME = "all";
export const ACTION_PARAM_ATTRIBUTE_ENTITY: CLIVerb = { name: ACTION_PARAM_ENTITY_NAME, type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTE_ATTRIBUTE: CLIVerb = { name: ACTION_PARAM_ATTRIBUTE_NAME, description: "Logical name of the attribute", type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTE_PROPERTIES: CLIVerb = { name: ACTION_PARAM_PROPERTIES_NAME, description: "CSV of the properties", type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTE_ALL: CLIVerb = { name: ACTION_PARAM_ATTRIBUTE_ALL_NAME, description: "Select this to return all properties", type: IntelliSenseType.ActionParams };
export const CLI_ACTION_PARAMS_GET_ATTRIBUTE: Array<CLIVerb> = [ACTION_PARAM_ATTRIBUTE_ENTITY,
    ACTION_PARAM_ATTRIBUTE_ATTRIBUTE,
    ACTION_PARAM_ATTRIBUTE_PROPERTIES,
    ACTION_PARAM_ATTRIBUTE_ALL];




export const ACTION_PARAM_ATTRIBUTES_TYPE_NAME = "type";
export const ACTION_PARAM_ATTRIBUTES_ENTITY: CLIVerb = { name: ACTION_PARAM_ENTITY_NAME, type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTES_TYPE: CLIVerb = { name: ACTION_PARAM_ATTRIBUTES_TYPE_NAME, description: "Proivde the attribute type", type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTES_PROPERTIES: CLIVerb = { name: ACTION_PARAM_PROPERTIES_NAME, description: "CSV of the properties", type: IntelliSenseType.ActionParams };
export const ACTION_PARAM_ATTRIBUTES_EXPAND: CLIVerb = { name: ACTION_PARAM_EXPAND_NAME, description: "Use to retrieve additional information", type: IntelliSenseType.ActionParams };
export const CLI_ACTION_PARAMS_GET_ATTRIBUTES: Array<CLIVerb> = [ACTION_PARAM_ATTRIBUTES_ENTITY,
    ACTION_PARAM_ATTRIBUTES_TYPE,
    ACTION_PARAM_ATTRIBUTES_PROPERTIES,
    ACTION_PARAM_ATTRIBUTES_EXPAND];



export const ACTION_PARAMS_ENTITY_ENTITY: CLIVerb = { name: ACTION_PARAM_ENTITY_NAME, type: IntelliSenseType.ActionParams };
export const ACTION_PARAMS_ENTITY_PROPERTIES: CLIVerb = { name: ACTION_PARAM_PROPERTIES_NAME, description: "CSV of the entity properties", type: IntelliSenseType.ActionParams };
export const ACTION_PARAMS_ENTITY_EXPAND: CLIVerb = { name: ACTION_PARAM_EXPAND_NAME, description: "Specify the relationships", type: IntelliSenseType.ActionParams };
export const CLI_ACTION_PARAMS_GET_ENTITY: Array<CLIVerb> = [ACTION_PARAMS_ENTITY_ENTITY,
    ACTION_PARAMS_ENTITY_PROPERTIES,
    ACTION_PARAMS_ENTITY_EXPAND];





export const ACTION_PARAM_ENTITIES_ENTITIES_NAME = "entities"
export const ACTION_PARAMS_ENTITIES_ENTITIES: CLIVerb = { name: ACTION_PARAM_ENTITIES_ENTITIES_NAME, description: "CSV of the entities", type: IntelliSenseType.ActionParams };
export const ACTION_PARAMS_ENTITIES_PROPERTIES: CLIVerb = { name: ACTION_PARAM_PROPERTIES_NAME, description: "CSV of the entity properties", type: IntelliSenseType.ActionParams };
export const ACTION_PARAMS_ENTITIES_FILTER: CLIVerb = { name: ACTION_PARAM_FILTER_NAME, description: "Specify the OData filter", type: IntelliSenseType.ActionParams };
export const CLI_ACTION_PARAMS_GET_ENTITIES: Array<CLIVerb> = [ACTION_PARAMS_ENTITIES_ENTITIES,
    ACTION_PARAMS_ENTITIES_FILTER,
    ACTION_PARAMS_ENTITIES_PROPERTIES];



export const GROUP_NAME_ODATA = "OData";
export const GROUP_NAME_FILTER_ATTRIBUTES = "Filter on Attributes";
export const ACTION_PARAM_GET_SELECT_NAME = "select";
export const ACTION_PARAM_GET_TOP_NAME = "top";
export const ACTION_PARAM_GET_ORDER_BY_NAME = "orderby";
export const ACTION_PARAM_GET_VIEW_NAME = "view";
export const ACTION_PARAMS_GET_FILTER: CLIVerb = { name: ACTION_PARAM_FILTER_NAME, description: "Provide the OData filter", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const ACTION_PARAMS_GET_LOGICAL_OPERATOR: CLIVerb = { name: ACTION_PARAM_FILTER_OPERATOR_NAME, description: "Specify the operator when using attributes", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const ACTION_PARAMS_GET_SELECT: CLIVerb = { name: ACTION_PARAM_GET_SELECT_NAME, description: "CSV of the attributes to be retrieved", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const ACTION_PARAMS_GET_TOP: CLIVerb = { name: ACTION_PARAM_GET_TOP_NAME, description: "Limits the number of results returned", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const ACTION_PARAMS_GET_ORDER_BY: CLIVerb = { name: ACTION_PARAM_GET_ORDER_BY_NAME, description: "Specify the order in which items are returned.", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const ACTION_PARAMS_GET_VIEW: CLIVerb = { name: ACTION_PARAM_GET_VIEW_NAME, description: "Specify the system or user view", type: IntelliSenseType.ActionParams, group: GROUP_NAME_ODATA, groupNumber: 1 };
export const CLI_ACTION_PARAMS_GET_RECORDS: Array<CLIVerb> = [ACTION_PARAMS_GET_FILTER,
    ACTION_PARAMS_GET_SELECT,
    ACTION_PARAMS_GET_TOP,
    ACTION_PARAMS_GET_LOGICAL_OPERATOR,
    ACTION_PARAMS_GET_ORDER_BY,
    ACTION_PARAMS_GET_VIEW];







//Common Operator Values
export const ACTION_PARAM_CONDITION_EQUALS = "eq";
export const ACTION_PARAM_CONDITION_DOES_NOT_EQUAL = "ne";
export const ACTION_PARAM_CONDITION_CONTAINS_DATA = "ne null";
export const ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA = "eq null";

//String Operator Values
export const ACTION_PARAM_CONDITION_CONTAINS = "contains";
export const ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN = "not contains";
export const ACTION_PARAM_CONDITION_BEGINS_WITH = "startswith";
export const ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH = "not startswith";
export const ACTION_PARAM_CONDITION_ENDS_WITH = "endswith";
export const ACTION_PARAM_CONDITION_DOES_NOT_END_WITH = "not endswith";

//Numeric Operator Values
export const ACTION_PARAM_CONDITION_GREATER_THAN = "gt";
export const ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL = "ge";
export const ACTION_PARAM_CONDITION_LESS_THAN = "lt";
export const ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL = "le";

//Lookup Operator Values
export const ACTION_PARAM_CONDITION_EQUAL_CURRENT_USER = "EqualUserId";
export const ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_CURRENT_USER = "NotEqualUserId";


//DateTime Operator Values
export const ACTION_PARAM_CONDITION_ON = "On";
export const ACTION_PARAM_CONDITION_ON_OR_AFTER = "OnOrAfter";
export const ACTION_PARAM_CONDITION_ON_OR_BEFORE = "OnOrBefore";
export const ACTION_PARAM_CONDITION_IN_FISCAL_YEAR = "InFiscalYear";
export const ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD = "InFiscalPeriod";
export const ACTION_PARAM_CONDITION_LASTX_FISCAL_PERIODS = "LastXFiscalPeriods";
export const ACTION_PARAM_CONDITION_LASTX_FISCAL_YEARS = "LastXFiscalYears";
export const ACTION_PARAM_CONDITION_NEXT_X_DAYS = "NextXDays";
export const ACTION_PARAM_CONDITION_NEXT_X_FISCAL_PERIODS = "NextXFiscalPeriods";
export const ACTION_PARAM_CONDITION_NEXT_X_FISCAL_YEARS = "NextXFiscalYears";
export const ACTION_PARAM_CONDITION_NEXT_X_HOURS = "NextXHours";
export const ACTION_PARAM_CONDITION_NEXT_X_MONTHS = "NextXMonths";
export const ACTION_PARAM_CONDITION_NEXT_X_WEEKS = "NextXWeeks";
export const ACTION_PARAM_CONDITION_NEXT_X_YEARS = "NextXYears";
export const ACTION_PARAM_CONDITION_LAST_X_HOURS = "LastXHours";
export const ACTION_PARAM_CONDITION_LAST_X_MONTHS = "LastXMonths";
export const ACTION_PARAM_CONDITION_LAST_X_WEEKS = "LastXWeeks";
export const ACTION_PARAM_CONDITION_LAST_X_YEARS = "LastXYears";
export const ACTION_PARAM_CONDITION_LAST_X_DAYS = "LastXDays";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_DAYS = "OlderThanXDays";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_HOURS = "OlderThanXHours";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_MINUTES = "OlderThanXMinutes";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_MONTHS = "OlderThanXMonths";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_WEEKS = "OlderThanXWeeks";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_YEARS = "OlderThanXYears";
export const ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_AND_YEAR = "InFiscalPeriodAndYear";


export const ACTION_PARAM_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR = "InOrAfterFiscalPeriodAndYear";
export const ACTION_PARAM_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR = "InOrBeforeFiscalPeriodAndYear";
export const ACTION_PARAM_CONDITION_LAST_7_DAYS = "Last7Days";
export const ACTION_PARAM_CONDITION_LAST_FISCAL_PERIOD = "LastFiscalPeriod";
export const ACTION_PARAM_CONDITION_LAST_FISCAL_YEAR = "LastFiscalYear";
export const ACTION_PARAM_CONDITION_LAST_YEAR = "LastYear";
export const ACTION_PARAM_CONDITION_NEXT_7_DAYS = "Next7Days";
export const ACTION_PARAM_CONDITION_NEXT_FISCAL_PERIOD = "NextFiscalPeriod";
export const ACTION_PARAM_CONDITION_NEXT_FISCAL_YEAR = "NextFiscalYear";

export const ACTION_PARAM_CONDITION_NEXT_MONTH = "NextMonth";
export const ACTION_PARAM_CONDITION_NEXT_WEEK = "NextWeek";
export const ACTION_PARAM_CONDITION_NEXT_YEAR = "NextYear";
export const ACTION_PARAM_CONDITION_LAST_MONTH = "LastMonth";
export const ACTION_PARAM_CONDITION_THIS_FISCAL_PERIOD = "ThisFiscalPeriod";
export const ACTION_PARAM_CONDITION_THIS_FISCAL_YEAR = "ThisFiscalYear";
export const ACTION_PARAM_CONDITION_THIS_MONTH = "ThisMonth";
export const ACTION_PARAM_CONDITION_THIS_WEEK = "ThisWeek";

export const ACTION_PARAM_CONDITION_THIS_YEAR = "ThisYear";
export const ACTION_PARAM_CONDITION_LAST_WEEK = "LastWeek";
export const ACTION_PARAM_CONDITION_TOMORROW = "Tomorrow";
export const ACTION_PARAM_CONDITION_TODAY = "Today";
export const ACTION_PARAM_CONDITION_YESTERDAY = "Yesterday";

export const REGULAR_CONDITION_OPERATORS = [
    ACTION_PARAM_CONDITION_EQUALS,
    ACTION_PARAM_CONDITION_DOES_NOT_EQUAL,
    ACTION_PARAM_CONDITION_CONTAINS_DATA,
    ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA,
    ACTION_PARAM_CONDITION_GREATER_THAN,
    ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL,
    ACTION_PARAM_CONDITION_LESS_THAN,
    ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL
];


export const STANDARD_QUERY_FUNCTION_CONDITION_OPERATORS = [ACTION_PARAM_CONDITION_CONTAINS,
    ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN,
    ACTION_PARAM_CONDITION_BEGINS_WITH,
    ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH,
    ACTION_PARAM_CONDITION_ENDS_WITH,
    ACTION_PARAM_CONDITION_DOES_NOT_END_WITH
];

export const CONDITION_OPERATORS = [
    ACTION_PARAM_CONDITION_EQUALS,
    ACTION_PARAM_CONDITION_DOES_NOT_EQUAL,
    ACTION_PARAM_CONDITION_CONTAINS_DATA,
    ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA,
    ACTION_PARAM_CONDITION_CONTAINS,
    ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN,
    ACTION_PARAM_CONDITION_BEGINS_WITH,
    ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH,
    ACTION_PARAM_CONDITION_ENDS_WITH,
    ACTION_PARAM_CONDITION_DOES_NOT_END_WITH,
    ACTION_PARAM_CONDITION_GREATER_THAN,
    ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL,
    ACTION_PARAM_CONDITION_LESS_THAN,
    ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL,
    ACTION_PARAM_CONDITION_EQUAL_CURRENT_USER,
    ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_CURRENT_USER,
    ACTION_PARAM_CONDITION_ON,
    ACTION_PARAM_CONDITION_ON_OR_AFTER,
    ACTION_PARAM_CONDITION_ON_OR_BEFORE,
    ACTION_PARAM_CONDITION_IN_FISCAL_YEAR,
    ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD,
    ACTION_PARAM_CONDITION_LASTX_FISCAL_PERIODS,
    ACTION_PARAM_CONDITION_LASTX_FISCAL_YEARS,
    ACTION_PARAM_CONDITION_NEXT_X_DAYS,
    ACTION_PARAM_CONDITION_NEXT_X_FISCAL_PERIODS,
    ACTION_PARAM_CONDITION_NEXT_X_FISCAL_YEARS,
    ACTION_PARAM_CONDITION_NEXT_X_HOURS,
    ACTION_PARAM_CONDITION_NEXT_X_MONTHS,
    ACTION_PARAM_CONDITION_NEXT_X_WEEKS,
    ACTION_PARAM_CONDITION_NEXT_X_YEARS,
    ACTION_PARAM_CONDITION_LAST_X_HOURS,
    ACTION_PARAM_CONDITION_LAST_X_MONTHS,
    ACTION_PARAM_CONDITION_LAST_X_WEEKS,
    ACTION_PARAM_CONDITION_LAST_X_YEARS,
    ACTION_PARAM_CONDITION_LAST_X_DAYS,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_DAYS,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_HOURS,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_MINUTES,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_MONTHS,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_WEEKS,
    ACTION_PARAM_CONDITION_OLDER_THAN_X_YEARS,
    ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAM_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAM_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAM_CONDITION_LAST_7_DAYS,
    ACTION_PARAM_CONDITION_LAST_FISCAL_PERIOD,
    ACTION_PARAM_CONDITION_LAST_FISCAL_YEAR,
    ACTION_PARAM_CONDITION_LAST_YEAR,
    ACTION_PARAM_CONDITION_NEXT_7_DAYS,
    ACTION_PARAM_CONDITION_NEXT_FISCAL_PERIOD,
    ACTION_PARAM_CONDITION_NEXT_FISCAL_YEAR,
    ACTION_PARAM_CONDITION_NEXT_MONTH,
    ACTION_PARAM_CONDITION_NEXT_WEEK,
    ACTION_PARAM_CONDITION_NEXT_YEAR,
    ACTION_PARAM_CONDITION_LAST_MONTH,
    ACTION_PARAM_CONDITION_THIS_FISCAL_PERIOD,
    ACTION_PARAM_CONDITION_THIS_FISCAL_YEAR,
    ACTION_PARAM_CONDITION_THIS_MONTH,
    ACTION_PARAM_CONDITION_THIS_WEEK,
    ACTION_PARAM_CONDITION_THIS_YEAR,
    ACTION_PARAM_CONDITION_LAST_WEEK,
    ACTION_PARAM_CONDITION_TOMORROW,
    ACTION_PARAM_CONDITION_TODAY,
    ACTION_PARAM_CONDITION_YESTERDAY
];

//Common Display Names
export const ACTION_PARAM_CONDITION_EQUALS_NAME = "Equals";
export const ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_NAME = "Does Not Equal";
export const ACTION_PARAM_CONDITION_CONTAINS_DATA_NAME = "Contains Data";
export const ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA_NAME = "Does Not Contain Data";

//String Display Names
export const ACTION_PARAM_CONDITION_CONTAINS_NAME = "Contains";
export const ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_NAME = "Does Not Contain";
export const ACTION_PARAM_CONDITION_BEGINS_WITH_NAME = "Begins With";
export const ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH_NAME = "Does Not Begin With";
export const ACTION_PARAM_CONDITION_ENDS_WITH_NAME = "Ends With";
export const ACTION_PARAM_CONDITION_DOES_NOT_END_WITH_NAME = "Does Not End With";

//Numeric Display Names
export const ACTION_PARAM_CONDITION_GREATER_THAN_NAME = "Is Greater Than";
export const ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL_NAME = "Is Greater Than or Equal To";
export const ACTION_PARAM_CONDITION_LESS_THAN_NAME = "Is Less Than";
export const ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL_NAME = "Is Less Than or Equal To";


//Lookup Display Names
export const ACTION_PARAM_CONDITION_EQUAL_CURRENT_USER_NAME = "Equals Current User";
export const ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_CURRENT_USER_NAME = "Does Not Equal Current User";



//DateTime Display Names
export const ACTION_PARAM_CONDITION_ON_NAME = "On";
export const ACTION_PARAM_CONDITION_ON_OR_AFTER_NAME = "OnOrAfter";
export const ACTION_PARAM_CONDITION_ON_OR_BEFORE_NAME = "OnOrBefore";
export const ACTION_PARAM_CONDITION_IN_FISCAL_YEAR_NAME = "InFiscalYear";
export const ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_NAME = "InFiscalPeriod";
export const ACTION_PARAM_CONDITION_LASTX_FISCAL_PERIODS_NAME = "LastXFiscalPeriods";
export const ACTION_PARAM_CONDITION_LASTX_FISCAL_YEARS_NAME = "LastXFiscalYears";
export const ACTION_PARAM_CONDITION_NEXT_X_DAYS_NAME = "NextXDays";
export const ACTION_PARAM_CONDITION_NEXT_X_FISCAL_PERIODS_NAME = "NextXFiscalPeriods";
export const ACTION_PARAM_CONDITION_NEXT_X_FISCAL_YEARS_NAME = "NextXFiscalYears";
export const ACTION_PARAM_CONDITION_NEXT_X_HOURS_NAME = "NextXHours";
export const ACTION_PARAM_CONDITION_NEXT_X_MONTHS_NAME = "NextXMonths";
export const ACTION_PARAM_CONDITION_NEXT_X_WEEKS_NAME = "NextXWeeks";
export const ACTION_PARAM_CONDITION_NEXT_X_YEARS_NAME = "NextXYears";
export const ACTION_PARAM_CONDITION_LAST_X_HOURS_NAME = "LastXHours";
export const ACTION_PARAM_CONDITION_LAST_X_MONTHS_NAME = "LastXMonths";
export const ACTION_PARAM_CONDITION_LAST_X_WEEKS_NAME = "LastXWeeks";
export const ACTION_PARAM_CONDITION_LAST_X_YEARS_NAME = "LastXYears";
export const ACTION_PARAM_CONDITION_LAST_X_DAYS_NAME = "LastXDays";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_DAYS_NAME = "OlderThanXDays";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_HOURS_NAME = "OlderThanXHours";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_MINUTES_NAME = "OlderThanXMinutes";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_MONTHS_NAME = "OlderThanXMonths";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_WEEKS_NAME = "OlderThanXWeeks";
export const ACTION_PARAM_CONDITION_OLDER_THAN_X_YEARS_NAME = "OlderThanXYears";
export const ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_AND_YEAR_NAME = "InFiscalPeriodAndYear";


export const ACTION_PARAM_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR_NAME = "InOrAfterFiscalPeriodAndYear";
export const ACTION_PARAM_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR_NAME = "InOrBeforeFiscalPeriodAndYear";
export const ACTION_PARAM_CONDITION_LAST_7_DAYS_NAME = "Last7Days";
export const ACTION_PARAM_CONDITION_LAST_FISCAL_PERIOD_NAME = "LastFiscalPeriod";
export const ACTION_PARAM_CONDITION_LAST_FISCAL_YEAR_NAME = "LastFiscalYear";
export const ACTION_PARAM_CONDITION_LAST_YEAR_NAME = "LastYear";
export const ACTION_PARAM_CONDITION_NEXT_7_DAYS_NAME = "Next7Days";
export const ACTION_PARAM_CONDITION_NEXT_FISCAL_PERIOD_NAME = "NextFiscalPeriod";
export const ACTION_PARAM_CONDITION_NEXT_FISCAL_YEAR_NAME = "NextFiscalYear";

export const ACTION_PARAM_CONDITION_NEXT_MONTH_NAME = "NextMonth";
export const ACTION_PARAM_CONDITION_NEXT_WEEK_NAME = "NextWeek";
export const ACTION_PARAM_CONDITION_NEXT_YEAR_NAME = "NextYear";
export const ACTION_PARAM_CONDITION_LAST_MONTH_NAME = "LastMonth";
export const ACTION_PARAM_CONDITION_THIS_FISCAL_PERIOD_NAME = "ThisFiscalPeriod";
export const ACTION_PARAM_CONDITION_THIS_FISCAL_YEAR_NAME = "ThisFiscalYear";
export const ACTION_PARAM_CONDITION_THIS_MONTH_NAME = "ThisMonth";
export const ACTION_PARAM_CONDITION_THIS_WEEK_NAME = "ThisWeek";

export const ACTION_PARAM_CONDITION_THIS_YEAR_NAME = "ThisYear";
export const ACTION_PARAM_CONDITION_LAST_WEEK_NAME = "LastWeek";
export const ACTION_PARAM_CONDITION_TOMORROW_NAME = "Tomorrow";
export const ACTION_PARAM_CONDITION_TODAY_NAME = "Today";
export const ACTION_PARAM_CONDITION_YESTERDAY_NAME = "Yesterday";





export const GROUP_NAME_COMMON_OPERATORS = "commonoperators";
export const GROUP_NAME_STRING_OPERATORS = "stringoperators";
export const GROUP_NAME_NUMERIC_OPERATORS = "numericoperators";

//Common Operators Verbs

export const ACTION_PARAMS_GET_CONDITION_EQUALS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_EQUALS_NAME,
    text: ACTION_PARAM_CONDITION_EQUALS,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_DOES_NOT_EQUAL: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_EQUAL,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_CONTAINS_DATA: CLIVerb = {
    name: ACTION_PARAM_CONDITION_CONTAINS_DATA_NAME,
    text: ACTION_PARAM_CONDITION_CONTAINS_DATA,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET__CONDITION_DOES_NOT_CONTAIN_DATA: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_DATA,
    type: IntelliSenseType.ActionParamValue
};

//String Operators Verbs

export const ACTION_PARAMS_GET_CONDITION_CONTAINS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_CONTAINS_NAME,
    text: ACTION_PARAM_CONDITION_CONTAINS,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_DOES_NOT_CONTAIN: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_CONTAIN,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_BEGINS_WITH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_BEGINS_WITH_NAME,
    text: ACTION_PARAM_CONDITION_BEGINS_WITH,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_DOES_NOT_BEGIN_WITH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_BEGIN_WITH,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_ENDS_WITH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_ENDS_WITH_NAME,
    text: ACTION_PARAM_CONDITION_ENDS_WITH,
    type: IntelliSenseType.ActionParamValue
};
export const ACTION_PARAMS_GET_CONDITION_DOES_NOT_ENDS_WITH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_END_WITH_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_END_WITH,
    type: IntelliSenseType.ActionParamValue
};


//Numeric Operator Verbs

export const ACTION_PARAMS_GET_CONDITION_IS_GREATER_THAN: CLIVerb = {
    name: ACTION_PARAM_CONDITION_GREATER_THAN_NAME,
    text: ACTION_PARAM_CONDITION_GREATER_THAN,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_IS_GREATER_THAN_OR_EQUAL_TO: CLIVerb = {
    name: ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL_NAME,
    text: ACTION_PARAM_CONDITION_GREATER_THAN_OR_EQUAL,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_IS_LESS_THAN: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LESS_THAN_NAME,
    text: ACTION_PARAM_CONDITION_LESS_THAN,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_IS_LESS_THAN_OR_EQUAL: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL_NAME,
    text: ACTION_PARAM_CONDITION_LESS_THAN_OR_EQUAL,
    type: IntelliSenseType.ActionParamValue
};


//Lookup Operator Verbs
export const ACTION_PARAMS_GET_CONDITION_EQUALS_CURRENT_USER: CLIVerb = {
    name: ACTION_PARAM_CONDITION_EQUAL_CURRENT_USER_NAME,
    text: ACTION_PARAM_CONDITION_EQUAL_CURRENT_USER,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_DOES_NOT_EQUAL_CURRENT_USER: CLIVerb = {
    name: ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_CURRENT_USER_NAME,
    text: ACTION_PARAM_CONDITION_DOES_NOT_EQUAL_CURRENT_USER,
    type: IntelliSenseType.ActionParamValue
};



//DateTime Operator Verbs


export const ACTION_PARAMS_GET_CONDITION_ON: CLIVerb = {
    name: ACTION_PARAM_CONDITION_ON_NAME,
    text: ACTION_PARAM_CONDITION_ON,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_ON_OR_AFTER: CLIVerb = {
    name: ACTION_PARAM_CONDITION_ON_OR_AFTER_NAME,
    text: ACTION_PARAM_CONDITION_ON_OR_AFTER,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_ON_OR_BEFORE: CLIVerb = {
    name: ACTION_PARAM_CONDITION_ON_OR_BEFORE_NAME,
    text: ACTION_PARAM_CONDITION_ON_OR_BEFORE,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_IN_FISCAL_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_IN_FISCAL_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_IN_FISCAL_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_IN_FISCAL_PERIOD: CLIVerb = {
    name: ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_NAME,
    text: ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LASTX_FISCAL_PERIODS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LASTX_FISCAL_PERIODS_NAME,
    text: ACTION_PARAM_CONDITION_LASTX_FISCAL_PERIODS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LASTX_FISCAL_YEARS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LASTX_FISCAL_YEARS_NAME,
    text: ACTION_PARAM_CONDITION_LASTX_FISCAL_YEARS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_X_DAYS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_DAYS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_DAYS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_NEXT_X_FISCAL_PERIODS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_FISCAL_PERIODS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_FISCAL_PERIODS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_X_FISCAL_YEARS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_FISCAL_YEARS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_FISCAL_YEARS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_X_HOURS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_HOURS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_HOURS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_X_MONTHS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_MONTHS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_MONTHS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_X_WEEKS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_WEEKS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_WEEKS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_NEXT_X_YEARS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_X_YEARS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_X_YEARS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_LAST_X_HOURS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_X_HOURS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_X_HOURS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_LAST_X_MONTHS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_X_MONTHS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_X_MONTHS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_LAST_X_WEEKS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_X_WEEKS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_X_WEEKS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_X_YEARS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_X_YEARS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_X_YEARS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_X_DAYS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_X_DAYS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_X_DAYS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_DAYS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_DAYS_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_DAYS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_HOURS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_HOURS_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_HOURS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_MINUTES: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_MINUTES_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_MINUTES,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_MONTHS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_MONTHS_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_MONTHS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_WEEKS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_WEEKS_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_WEEKS,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_YEARS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_OLDER_THAN_X_YEARS_NAME,
    text: ACTION_PARAM_CONDITION_OLDER_THAN_X_YEARS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_IN_FISCAL_PERIOD_AND_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_AND_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_IN_FISCAL_PERIOD_AND_YEAR,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_7_DAYS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_7_DAYS_NAME,
    text: ACTION_PARAM_CONDITION_LAST_7_DAYS,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_LAST_FISCAL_PERIOD: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_FISCAL_PERIOD_NAME,
    text: ACTION_PARAM_CONDITION_LAST_FISCAL_PERIOD,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_LAST_FISCAL_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_FISCAL_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_LAST_FISCAL_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_LAST_YEAR,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_7_DAYS: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_7_DAYS_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_7_DAYS,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_NEXT_FISCAL_PERIOD: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_FISCAL_PERIOD_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_FISCAL_PERIOD,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_FISCAL_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_FISCAL_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_FISCAL_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_NEXT_MONTH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_MONTH_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_MONTH,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_NEXT_WEEK: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_WEEK_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_WEEK,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_NEXT_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_NEXT_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_NEXT_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_MONTH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_MONTH_NAME,
    text: ACTION_PARAM_CONDITION_LAST_MONTH,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_THIS_FISCAL_PERIOD: CLIVerb = {
    name: ACTION_PARAM_CONDITION_THIS_FISCAL_PERIOD_NAME,
    text: ACTION_PARAM_CONDITION_THIS_FISCAL_PERIOD,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_THIS_FISCAL_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_THIS_FISCAL_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_THIS_FISCAL_YEAR,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_THIS_MONTH: CLIVerb = {
    name: ACTION_PARAM_CONDITION_THIS_MONTH_NAME,
    text: ACTION_PARAM_CONDITION_THIS_MONTH,
    type: IntelliSenseType.ActionParamValue
};

export const ACTION_PARAMS_GET_CONDITION_THIS_WEEK: CLIVerb = {
    name: ACTION_PARAM_CONDITION_THIS_WEEK_NAME,
    text: ACTION_PARAM_CONDITION_THIS_WEEK,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_THIS_YEAR: CLIVerb = {
    name: ACTION_PARAM_CONDITION_THIS_YEAR_NAME,
    text: ACTION_PARAM_CONDITION_THIS_YEAR,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_LAST_WEEK: CLIVerb = {
    name: ACTION_PARAM_CONDITION_LAST_WEEK_NAME,
    text: ACTION_PARAM_CONDITION_LAST_WEEK,
    type: IntelliSenseType.ActionParamValue
};


export const ACTION_PARAMS_GET_CONDITION_TOMORROW: CLIVerb = {
    name: ACTION_PARAM_CONDITION_TOMORROW_NAME,
    text: ACTION_PARAM_CONDITION_TOMORROW,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_TODAY: CLIVerb = {
    name: ACTION_PARAM_CONDITION_TODAY_NAME,
    text: ACTION_PARAM_CONDITION_TODAY,
    type: IntelliSenseType.ActionParamValue
};



export const ACTION_PARAMS_GET_CONDITION_YESTERDAY: CLIVerb = {
    name: ACTION_PARAM_CONDITION_YESTERDAY_NAME,
    text: ACTION_PARAM_CONDITION_YESTERDAY,
    type: IntelliSenseType.ActionParamValue
};



//Common
export const CLI_ACTION_PARAMS_GET_COMMON_CONDITIONS: Array<CLIVerb> = [
    ACTION_PARAMS_GET_CONDITION_EQUALS,
    ACTION_PARAMS_GET_CONDITION_DOES_NOT_EQUAL,
    ACTION_PARAMS_GET_CONDITION_CONTAINS_DATA,
    ACTION_PARAMS_GET__CONDITION_DOES_NOT_CONTAIN_DATA];

//String
export const CLI_ACTION_PARAMS_GET_STRING_CONDITIONS: Array<CLIVerb> = [
    ACTION_PARAMS_GET_CONDITION_CONTAINS,
    ACTION_PARAMS_GET_CONDITION_DOES_NOT_CONTAIN,
    ACTION_PARAMS_GET_CONDITION_BEGINS_WITH,
    ACTION_PARAMS_GET_CONDITION_DOES_NOT_BEGIN_WITH,
    ACTION_PARAMS_GET_CONDITION_ENDS_WITH,
    ACTION_PARAMS_GET_CONDITION_DOES_NOT_ENDS_WITH];


//Numeric
export const CLI_ACTION_PARAMS_GET_NUMERIC_CONDITIONS: Array<CLIVerb> = [
    ACTION_PARAMS_GET_CONDITION_IS_GREATER_THAN,
    ACTION_PARAMS_GET_CONDITION_IS_GREATER_THAN_OR_EQUAL_TO,
    ACTION_PARAMS_GET_CONDITION_IS_LESS_THAN,
    ACTION_PARAMS_GET_CONDITION_IS_LESS_THAN_OR_EQUAL
];



//Lookup
export const CLI_ACTION_PARAMS_GET_LOOKUP_CONDITIONS: Array<CLIVerb> = [
    ACTION_PARAMS_GET_CONDITION_EQUALS_CURRENT_USER,
    ACTION_PARAMS_GET_CONDITION_DOES_NOT_EQUAL_CURRENT_USER

];



export const CLI_ACTION_PARAMS_GET_DATETIME_CONDITIONS: Array<CLIVerb> = [
    ACTION_PARAMS_GET_CONDITION_ON,
    ACTION_PARAMS_GET_CONDITION_ON_OR_AFTER,
    ACTION_PARAMS_GET_CONDITION_ON_OR_BEFORE,
    ACTION_PARAMS_GET_CONDITION_IN_FISCAL_YEAR,
    ACTION_PARAMS_GET_CONDITION_IN_FISCAL_PERIOD,
    ACTION_PARAMS_GET_CONDITION_LASTX_FISCAL_PERIODS,
    ACTION_PARAMS_GET_CONDITION_LASTX_FISCAL_YEARS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_DAYS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_FISCAL_PERIODS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_FISCAL_YEARS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_HOURS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_MONTHS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_WEEKS,
    ACTION_PARAMS_GET_CONDITION_NEXT_X_YEARS,
    ACTION_PARAMS_GET_CONDITION_LAST_X_HOURS,
    ACTION_PARAMS_GET_CONDITION_LAST_X_MONTHS,
    ACTION_PARAMS_GET_CONDITION_LAST_X_WEEKS,
    ACTION_PARAMS_GET_CONDITION_LAST_X_YEARS,
    ACTION_PARAMS_GET_CONDITION_LAST_X_DAYS,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_DAYS,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_HOURS,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_MINUTES,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_MONTHS,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_WEEKS,
    ACTION_PARAMS_GET_CONDITION_OLDER_THAN_X_YEARS,
    ACTION_PARAMS_GET_CONDITION_IN_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAMS_GET_CONDITION_IN_OR_AFTER_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAMS_GET_CONDITION_IN_OR_BEFORE_FISCAL_PERIOD_AND_YEAR,
    ACTION_PARAMS_GET_CONDITION_LAST_7_DAYS,
    ACTION_PARAMS_GET_CONDITION_LAST_FISCAL_PERIOD,
    ACTION_PARAMS_GET_CONDITION_LAST_FISCAL_YEAR,
    ACTION_PARAMS_GET_CONDITION_LAST_YEAR,
    ACTION_PARAMS_GET_CONDITION_NEXT_7_DAYS,
    ACTION_PARAMS_GET_CONDITION_NEXT_FISCAL_PERIOD,
    ACTION_PARAMS_GET_CONDITION_NEXT_FISCAL_YEAR,  
    ACTION_PARAMS_GET_CONDITION_NEXT_MONTH,
    ACTION_PARAMS_GET_CONDITION_NEXT_WEEK,
    ACTION_PARAMS_GET_CONDITION_NEXT_YEAR,
    ACTION_PARAMS_GET_CONDITION_LAST_MONTH,
    ACTION_PARAMS_GET_CONDITION_THIS_FISCAL_PERIOD,
    ACTION_PARAMS_GET_CONDITION_THIS_FISCAL_YEAR,
    ACTION_PARAMS_GET_CONDITION_THIS_MONTH,
    ACTION_PARAMS_GET_CONDITION_THIS_WEEK,  
    ACTION_PARAMS_GET_CONDITION_THIS_YEAR,
    ACTION_PARAMS_GET_CONDITION_LAST_WEEK,
    ACTION_PARAMS_GET_CONDITION_TOMORROW,
    ACTION_PARAMS_GET_CONDITION_TODAY,
    ACTION_PARAMS_GET_CONDITION_YESTERDAY
];
